server:
  port: 8765
spring:
  application:
    name: api-gateway-server
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: main-app
        uri: lb://main-app
        predicates:
        - Path=/product/**
        filters:
        - RewritePath=/(?<segment>.*), /$\{segment}
      - id: calculator-service
        uri: lb://calculator-service
        predicates:
        - Path=/calculator/**
        filters:
        - RewritePath=/(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO
