spring:
  application:
    name: calculator-service
  cloud:
    discovery:
      enabled: true

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

service:
  main-app: ${MAIN_SERVICE:http://main-app/}