# H2
spring:
  main:
    banner-mode: off
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  application:
    name: main-app
  cloud:
    discovery:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/product?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USER:zac}
    password: ${DB_PASSWORD:newAdmin}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #org.hibernate.dialect.H2Dialect
      #create-drop
  sql:
    init:
      platform: mysql
      mode: always

scheduler:
  frequency: ${FREQUENCY:10000}

export:
  path: ${EXPORT_PATH:export/product.csv}

service:
  storage: ${STORAGE_SERVICE:http://storage-service/storage}
  calculator: ${CALCULATOR_SERVICE:http://calculator-service/calculator}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:testdb
##    url: jdbc:h2:file:~/test
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver

server:
  port: 8081

