# H2
spring:
  main:
    banner-mode: off
  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS
  application:
    name: ProductService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_duplica?createDatabaseIfNotExist=true
    username: zac
    password: newAdmin
    platform: mysql
    initialization-mode: always

    jpa:
      generate-ddl: true
      hibernate.ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      #org.hibernate.dialect.H2Dialect
      #create-drop

server:
  port: 8084