# H2
spring:
  main:
    banner-mode: off
  application:
    name: storage-service
  cloud:
    discovery:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/storage?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USER:zac}
    password: ${DB_PASSWORD:newAdmin}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode:
      platform: mysql

scheduler:
  frequency: ${FREQUENCY:10000}

app:
  import-from-csv: false

service:
  main-app: ${MAIN_SERVICE:http://main-app/}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

server:
  port: 8084